export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "OPEN_MODAL";

export const OPEN_DESIGNER_MEN = "OPEN_DESIGNER_MEN";
export const OPEN_DESIGNER_WOMEN = "OPEN_DESIGNER_WOMEN";

export const FETCH_TSHIRTS = "FETCH_TSHIRTS";
export const FETCH_TSHIRTS_START = "FETCH_TSHIRTS_START";
export const FETCH_TSHIRTS_FAILED = "FETCH_TSHIRTS_FAILED";

export const TSHIRT_GENDER = "TSHIRT_GENDER";
export const TSHIRT_SIZE = "TSHIRT_SIZE";
export const TSHIRT_TYPE = "TSHIRT_TYPE";
export const TSHIRT_COLOR = "TSHIRT_COLOR";
export const TSHIRT_DESCRIPTION = "TSHIRT_DESCRIPTION";
export const TSHIRT_PRICE = "TSHIRT_PRICE";
export const TSHIRT_ORDERING = "TSHIRT_ORDERING";
export const TSHIRT_QUANTITY = "TSHIRT_QUANTITY";

export const CART_ITEMS = "CART_ITEMS";
export const CART_TOTAL_PRICE = "CART_TOTAL_PRICE";

export const SAVE_ORDER = "SAVE_ORDER";
export const SAVE_ORDER_START = "SAVE_ORDER_START";
export const SAVE_ORDER_FAILED = "SAVE_ORDER_FAILED";

export const AUTH = "AUTH";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_EMAIL = "AUTH_EMAIL";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";

